from common.insights.selectors.insight_selector import InsightSelector


class ChartHelper:
    """Helper class for generating chart configurations."""

    @staticmethod
    def get_kpi_data() -> list[dict]:
        """Generate KPI cards data."""
        revenue_data = InsightSelector.get_total_revenue()
        customers_count = InsightSelector.get_total_active_customer()
        orders_count = InsightSelector.get_total_paid_orders()

        return [
            {
                "title": "Total Customers",
                "metric": customers_count,
                "display": str(customers_count),
            },
            {
                "title": "TOTAL Revenue",
                "metric": revenue_data["value"],
                "display": revenue_data["display"],
            },
            {
                "title": "TOTAL Orders",
                "metric": orders_count,
                "display": str(orders_count),
            },
        ]

    @staticmethod
    def format_line_chart_data() -> dict[str, dict[str, dict[str, list]]]:
        payments_sessions_data = {
            "payments": {
                "monthly": {
                    "labels": [
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6",
                        "7",
                        "8",
                        "9",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "19",
                        "20",
                        "21",
                        "22",
                        "23",
                        "24",
                        "25",
                        "26",
                        "27",
                        "28",
                        "29",
                        "30",
                        "31",
                    ],
                    "datasets": [
                        {
                            "type": "line",
                            "data": [
                                120,
                                185,
                                160,
                                210,
                                245,
                                220,
                                280,
                                265,
                                290,
                                320,
                                295,
                                340,
                                315,
                                275,
                                380,
                                350,
                                290,
                                310,
                                425,
                                390,
                                360,
                                415,
                                440,
                                380,
                                395,
                                420,
                                485,
                                450,
                                475,
                                520,
                                500,
                            ],
                            "borderColor": "#10b981",
                            "pointBorderColor": "#10b981",
                            "pointBackgroundColor": "#10b981",
                        }
                    ],
                },
                "yearly": {
                    "labels": [
                        "Jan",
                        "Feb",
                        "Mar",
                        "Apr",
                        "May",
                        "Jun",
                        "Jul",
                        "Aug",
                        "Sep",
                        "Oct",
                        "Nov",
                        "Dec",
                    ],
                    "datasets": [
                        {
                            "type": "line",
                            "data": [
                                8500,
                                9200,
                                10100,
                                11800,
                                12450,
                                13200,
                                14800,
                                15650,
                                16900,
                                12000,
                                0,
                                0,
                            ],
                            "borderColor": "#10b981",
                            "pointBorderColor": "#10b981",
                            "pointBackgroundColor": "#10b981",
                        }
                    ],
                },
            },
            "orders": {
                "monthly": {
                    "labels": [
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6",
                        "7",
                        "8",
                        "9",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "19",
                        "20",
                        "21",
                        "22",
                        "23",
                        "24",
                        "25",
                        "26",
                        "27",
                        "28",
                        "29",
                        "30",
                        "31",
                    ],
                    "datasets": [
                        {
                            "type": "line",
                            "data": [
                                15,
                                22,
                                18,
                                25,
                                30,
                                28,
                                35,
                                32,
                                38,
                                42,
                                39,
                                45,
                                41,
                                37,
                                48,
                                44,
                                40,
                                43,
                                52,
                                49,
                                46,
                                51,
                                55,
                                48,
                                50,
                                53,
                                58,
                                56,
                                59,
                                62,
                                60,
                            ],
                            "borderColor": "#6366f1",
                            "pointBorderColor": "#6366f1",
                            "pointBackgroundColor": "#6366f1",
                        }
                    ],
                },
                "yearly": {
                    "labels": [
                        "Jan",
                        "Feb",
                        "Mar",
                        "Apr",
                        "May",
                        "Jun",
                        "Jul",
                        "Aug",
                        "Sep",
                        "Oct",
                        "Nov",
                        "Dec",
                    ],
                    "datasets": [
                        {
                            "type": "line",
                            "data": [
                                420,
                                485,
                                520,
                                680,
                                750,
                                820,
                                890,
                                965,
                                1020,
                                800,
                                0,
                                0,
                            ],
                            "borderColor": "#6366f1",
                            "pointBorderColor": "#6366f1",
                            "pointBackgroundColor": "#6366f1",
                        }
                    ],
                },
            },
        }
        return payments_sessions_data
