#name: 'OpenCommit Action'
#
#on:
#  push:
#    branches-ignore: [ main, master, dev, development, release ]  # prevent rebasing shared branches
#
#jobs:
#  opencommit:
#    runs-on: ubuntu-latest
#    permissions: write-all
#    steps:
#      - uses: actions/checkout@v5
#        with:
#          fetch-depth: 0
#
#      - uses: actions/setup-node@v5
#        with:
#          node-version: '16'
#
#      - uses: di-sukharev/opencommit@github-action-v1.0.4
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        env:
#          OCO_OPENAI_API_KEY: ${{ secrets.OCO_API_KEY }}
#          OCO_MODEL: gpt-4o-mini
#          OCO_EMOJI: true
#          OCO_DESCRIPTION: true
#          OCO_LANGUAGE: en
