version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: 'compose/local/django/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      django-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    directory: 'compose/local/docs/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      docs-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    directory: 'compose/local/node/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      node-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'docker'
    directory: 'compose/prod/aws/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      aws-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'docker'
    directory: 'compose/prod/django/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      django-prod-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    directory: 'compose/prod/postgres/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      postgres-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'docker'
    directory: 'compose/prod/traefik/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5
    versioning-strategy:
      increase: "patch"
    groups:
      traefik-dependencies:
        patterns:
          - "*"

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    open-pull-requests-limit: 10
    versioning-strategy:
      increase: "patch"
      update-type: "semver:minor"
    groups:
      python-dependencies:
        patterns:
          - "*"
