name: Deploy to Dev
on:
  push:
    branches: [ main ]

jobs:
  verify-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security checks
        run: |
          bandit -r .
          safety check -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to App Runner (Dev)
        run: |
          aws apprunner update-service \
            --service-arn ${{ secrets.DEV_APP_RUNNER_ARN }} \
            --source-configuration "ImageRepository={ImageIdentifier=$ECR_URI:main,ImageRepositoryType=ECR}"
