volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }


services:
  django:
    build:
      context: .
      dockerfile: compose/prod/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
        - .env
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/prod/postgres/Dockerfile
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
        - .env

  traefik:
    build:
      context: .
      dockerfile: compose/prod/traefik/Dockerfile
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    env_file:
        - .env

  redis:
    image: docker.io/redis:6

  awscli:
    build:
      context: .
      dockerfile: compose/prod/aws/Dockerfile
    env_file:
        - .env
    volumes:
      - production_postgres_data_backups:/backups:z
