volumes:
  projectname_local_postgres_data: { }

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        is_local: 'true'
    container_name: projectname_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv  # Anonymous volume for .venv (must be first)
      - .:/app:z    # Mount source code
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DATABASE_URL: 'postgis://postgres:postgres@postgres:5432/mydatabase' # pragma: allowlist secret

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: projectname_frontend
    depends_on:
      - django
    volumes:
      - ./frontend/src:/code/src:z
      - ./frontend/public:/code/public:z
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot reload in Docker
      - REACT_APP_API_URL=http://localhost:8000

  postgres:
    image: imresamu/postgis:17-3.5.0-alpine3.20
    container_name: projectname_postgres
    volumes:
      - projectname_local_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres' # pragma: allowlist secret
