volumes:
  temp_project_local_postgres_data: {}
  temp_project_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'
    command: /start
    environment:
      # Embedded environment variables for Django
      ENVIRONMENT: 'local'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_password' # pragma: allowlist secret
      AWS_SECRETS_REGION: ${AWS_SECRETS_REGION}
      AWS_SECRET_ID: ${AWS_SECRET_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}


  postgres:
    build:
      context: .
      dockerfile: compose/prod/postgres/Dockerfile
    container_name: postgres
    volumes:
      - temp_project_local_postgres_data:/var/lib/postgresql/data
      - temp_project_local_postgres_data_backups:/backups
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_password' # pragma: allowlist secret
