volumes:
  temp_project_local_postgres_data: { }
  temp_project_local_postgres_data_backups: { }


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: temp_project_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      - CI=${CI:-false}
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/prod/postgres/Dockerfile
    container_name: temp_project_local_postgres
    volumes:
      - temp_project_local_postgres_data:/var/lib/postgresql/data
      - temp_project_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'
