volumes:
  project_name_local_postgres_data: { }
  project_name_local_postgres_data_backups: { }
  project_name_local_redis_data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: project_name_local_django
    container_name: project_name_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: project_name_production_postgres
    ports:
      - "5432:5432"
    container_name: project_name_local_postgres
    volumes:
      - project_name_local_postgres_data:/var/lib/postgresql/data
      - project_name_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres



  redis:
    image: docker.io/redis:6
    container_name: project_name_local_redis

    volumes:
      - project_name_local_redis_data:/data


#  celeryworker:
#    <<: *django
#    image: project_name_local_celeryworker
#    container_name: project_name_local_celeryworker
#    depends_on:
#      - redis
#      - postgres
#    ports: []
#    command: /start-celeryworker
#
#  celerybeat:
#    <<: *django
#    image: project_name_local_celerybeat
#    container_name: project_name_local_celerybeat
#    depends_on:
#      - redis
#      - postgres
#    ports: []
#    command: /start-celerybeat
#
#  flower:
#    <<: *django
#    image: project_name_local_flower
#    container_name: project_name_local_flower
#    ports:
#      - '5555:5555'
#    command: /start-flower
