# Generated by Django 5.2.1 on 2025-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('message_body', models.TextField(verbose_name='Message Body')),
                ('message_body_ar', models.TextField(null=True, verbose_name='Message Body')),
                ('message_body_en', models.TextField(null=True, verbose_name='Message Body')),
                ('notification_type', models.CharField(choices=[('product_ordered', 'Product Ordered'), ('other', 'Other')], default='other', verbose_name='Notification Type')),
                ('send_sms', models.BooleanField(verbose_name='Send SMS')),
                ('send_fcm', models.BooleanField(verbose_name='Send FCM')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
