# Generated by Django 5.2.7 on 2025-10-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_ordered', 'Product Ordered'), ('other', 'Other'), ('referral_app_install', 'Referral App Install'), ('referral_first_order', 'Referral First Order'), ('money_added', 'Money Added')], default='other', max_length=50, verbose_name='Notification Type'),
        ),
    ]
