# Generated by Django 5.2.5 on 2025-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('product_ordered', 'Product Ordered'), ('other', 'Other'), ('referral_app_install', 'Referral App Install'), ('referral_first_order', 'Referral First Order'), ('money_added', 'Money Added')], default='other', verbose_name='Notification Type'),
        ),
    ]
