# Generated by Django 5.2.7 on 2025-10-27 10:00

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, help_text='Description about the organization.', verbose_name='About Us')),
                ('about_us_ar', models.TextField(blank=True, help_text='Description about the organization.', null=True, verbose_name='About Us')),
                ('about_us_en', models.TextField(blank=True, help_text='Description about the organization.', null=True, verbose_name='About Us')),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions for organization.', verbose_name='Terms of Service')),
                ('terms_ar', models.TextField(blank=True, help_text='Terms and conditions for organization.', null=True, verbose_name='Terms of Service')),
                ('terms_en', models.TextField(blank=True, help_text='Terms and conditions for organization.', null=True, verbose_name='Terms of Service')),
                ('policy', models.TextField(blank=True, help_text='Privacy policy details for the organization.', verbose_name='Privacy Policy')),
                ('policy_ar', models.TextField(blank=True, help_text='Privacy policy details for the organization.', null=True, verbose_name='Privacy Policy')),
                ('policy_en', models.TextField(blank=True, help_text='Privacy policy details for the organization.', null=True, verbose_name='Privacy Policy')),
            ],
            options={
                'verbose_name': 'Application Information',
                'verbose_name_plural': 'Application Information',
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Group Name')),
                ('name_ar', models.CharField(max_length=255, null=True, unique=True, verbose_name='Group Name')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Group Name')),
                ('order', models.PositiveIntegerField(help_text='Group Ordering Level', verbose_name='Order')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Group',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('GENERAL', 'General'), ('SUPPORT', 'Support'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other'), ('COMPLAINT', 'Complaint')], max_length=50, verbose_name='Contact Type')),
                ('description', models.TextField(help_text='Please provide a detailed description of your issue or inquiry.', verbose_name='Description')),
                ('has_checked', models.BooleanField(default=False, verbose_name='Has Checked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ar', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ar', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPopUpBanner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100, verbose_name='Image Banner')),
                ('count_per_user', models.PositiveIntegerField(help_text='Number of times this banner will be shown to each user', verbose_name='Display count per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup banner is active and can be displayed', verbose_name='Is Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Banner',
                'verbose_name_plural': 'historical Banners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('title_ar', models.CharField(default='', max_length=255, null=True)),
                ('title_en', models.CharField(default='', max_length=255, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='onboarding/', verbose_name='Image')),
                ('text', models.TextField(help_text='You can only wirte 75 characters.', max_length=75, verbose_name='Text')),
                ('text_ar', models.TextField(help_text='You can only wirte 75 characters.', max_length=75, null=True, verbose_name='Text')),
                ('text_en', models.TextField(help_text='You can only wirte 75 characters.', max_length=75, null=True, verbose_name='Text')),
                ('sub_text', models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, verbose_name='Sub Text')),
                ('sub_text_ar', models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, null=True, verbose_name='Sub Text')),
                ('sub_text_en', models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, null=True, verbose_name='Sub Text')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboarding',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopUpBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='popups/', verbose_name='Image Banner')),
                ('count_per_user', models.PositiveIntegerField(help_text='Number of times this banner will be shown to each user', verbose_name='Display count per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup banner is active and can be displayed', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='PopUpTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(help_text='Number of times this user has viewed this banner', verbose_name='View Count')),
            ],
            options={
                'verbose_name': 'Popup Tracking',
                'verbose_name_plural': 'Popup Trackings',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Phones start with: '+20'/'+966'", max_length=15, null=True, region=None, verbose_name='Phone Number')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Account')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Account')),
                ('tiktok', models.URLField(blank=True, verbose_name='Tiktok Account')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='banners/', verbose_name='Image Banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='appInfo.bannergroup', verbose_name='Banner Group')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
