# Generated by Django 5.0.6 on 2024-07-17 15:57

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField(blank=True, help_text='Information about the company or service.', null=True)),
                ('content_ar', models.TextField(blank=True, help_text='Information about the company or service in Arabic.', null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Phones start with: '+20'/'+966'", max_length=15, null=True, region=None, verbose_name='Phone Number')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Account')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Account')),
                ('tiktok', models.URLField(blank=True, verbose_name='Tiktok Account')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField(blank=True, help_text='Terms and Conditions of the website.', null=True, verbose_name='Content (EN)')),
                ('content_ar', models.TextField(blank=True, help_text='Terms and Conditions of the website in Arabic.', null=True, verbose_name='Content (AR)')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
            },
        ),
    ]
