# Generated by Django 5.2.1 on 2025-05-25 11:10

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, help_text='Description about the organization.', verbose_name='About Us')),
                ('about_us_ar', models.TextField(blank=True, help_text='Description about the organization.', null=True, verbose_name='About Us')),
                ('about_us_en', models.TextField(blank=True, help_text='Description about the organization.', null=True, verbose_name='About Us')),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions for organization.', verbose_name='Terms of Service')),
                ('terms_ar', models.TextField(blank=True, help_text='Terms and conditions for organization.', null=True, verbose_name='Terms of Service')),
                ('terms_en', models.TextField(blank=True, help_text='Terms and conditions for organization.', null=True, verbose_name='Terms of Service')),
                ('policy', models.TextField(blank=True, help_text='Privacy policy details for the organization.', verbose_name='Privacy Policy')),
                ('policy_ar', models.TextField(blank=True, help_text='Privacy policy details for the organization.', null=True, verbose_name='Privacy Policy')),
                ('policy_en', models.TextField(blank=True, help_text='Privacy policy details for the organization.', null=True, verbose_name='Privacy Policy')),
            ],
            options={
                'verbose_name': 'Application Information',
                'verbose_name_plural': 'Application Information',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ar', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ar', models.TextField(null=True)),
                ('answer_en', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0, unique=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Phones start with: '+20'/'+966'", max_length=15, null=True, region=None, verbose_name='Phone Number')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter Account')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram Account')),
                ('tiktok', models.URLField(blank=True, verbose_name='Tiktok Account')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_fees', models.DecimalField(decimal_places=2, default=0.0, help_text='cancellation feed.', max_digits=6, verbose_name='Cancellation Fees')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
