# Generated by Django 5.2.1 on 2025-07-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0001_initial'),
        ('users', '0002_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('GENERAL', 'General'), ('SUPPORT', 'Support'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other'), ('COMPLAINT', 'Complaint')], max_length=50, verbose_name='Contact Type')),
                ('description', models.TextField(help_text='Please provide a detailed description of your issue or inquiry.', verbose_name='Description')),
                ('has_checked', models.BooleanField(default=False, verbose_name='Has Checked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('customer', models.ForeignKey(help_text='Select the customer who is making this contact.', on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Customer')),
            ],
        ),
    ]
