# Generated by Django 5.2.7 on 2025-10-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appInfo', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='customer',
            field=models.ForeignKey(help_text='Select the customer who is making this contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='historicalpopupbanner',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popuptracking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='popuptracking',
            name='popup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='appInfo.popupbanner', verbose_name='Popup Banner'),
        ),
    ]
