# Generated by Django 5.2.5 on 2025-08-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemConfig',
        ),
    ]
