# Generated by Django 5.2.1 on 2025-07-31 08:23

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='onboarding/', verbose_name='Image')),
                ('text', models.TextField(help_text='You can only wirte 75 characters.', max_length=75, verbose_name='Text')),
                ('sub_text', models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, verbose_name='Sub Text')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboarding',
                'ordering': ['order'],
            },
        ),
    ]
