# Generated by Django 5.2.8 on 2026-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Question'),
        ),
    ]
