# Generated by Django 5.2.1 on 2025-07-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0003_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='sub_text_ar',
            field=models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, null=True, verbose_name='Sub Text'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='sub_text_en',
            field=models.TextField(default='', help_text='You can only wirte 50 characters.', max_length=50, null=True, verbose_name='Sub Text'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='text_ar',
            field=models.TextField(help_text='You can only wirte 75 characters.', max_length=75, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='text_en',
            field=models.TextField(help_text='You can only wirte 75 characters.', max_length=75, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='title_ar',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='title_en',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
