# Generated by Django 5.2.8 on 2026-01-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0003_alter_faq_answer_alter_faq_answer_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us Entries'},
        ),
    ]
