# Generated by Django 5.2.5 on 2025-08-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0003_delete_systemconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
