# Generated by Django 5.2.5 on 2025-10-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='customer',
            field=models.ForeignKey(help_text='Select the customer who is making this contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer', verbose_name='Customer'),
        ),
    ]
