# Generated by Django 5.2.1 on 2025-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0004_onboarding_sub_text_ar_onboarding_sub_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Group Name')),
                ('order', models.PositiveIntegerField(help_text='Group Ordering Level', verbose_name='Order')),
                ('is_active', models.BooleanField(verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Group',
            },
        ),
    ]
