# Generated by Django 5.2.1 on 2025-07-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0005_bannergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannergroup',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Group Name'),
        ),
        migrations.AddField(
            model_name='bannergroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Group Name'),
        ),
    ]
