# Generated by Django 5.2.1 on 2025-07-31 08:37

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0006_bannergroup_name_ar_bannergroup_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='banners/', verbose_name='Image Banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='appInfo.bannergroup', verbose_name='Banner Group')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
