# Generated by Django 5.2.1 on 2025-07-31 08:42

import django.db.models.deletion
import imagekit.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0007_banner'),
        ('users', '0002_alter_customer_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='popups/', verbose_name='Image Banner')),
                ('count_per_user', models.PositiveIntegerField(help_text='Number of times this banner will be shown to each user', verbose_name='Display count per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup banner is active and can be displayed', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPopUpBanner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(max_length=100, verbose_name='Image Banner')),
                ('count_per_user', models.PositiveIntegerField(help_text='Number of times this banner will be shown to each user', verbose_name='Display count per user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this popup banner is active and can be displayed', verbose_name='Is Active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banner',
                'verbose_name_plural': 'historical Banners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PopUpTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(help_text='Number of times this user has viewed this banner', verbose_name='View Count')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Customer')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='appInfo.popupbanner', verbose_name='Popup Banner')),
            ],
            options={
                'verbose_name': 'Popup Tracking',
                'verbose_name_plural': 'Popup Trackings',
            },
        ),
    ]
