# Generated by Django 5.2.5 on 2025-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0008_popupbanner_historicalpopupbanner_popuptracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='referral_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for referring a new user.', verbose_name='Referral Points'),
        ),
    ]
