# Generated by Django 5.2.5 on 2025-08-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0009_systemconfig_referral_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='referral_points',
        ),
    ]
