# Generated by Django 5.2.5 on 2025-08-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_customer_id',
            field=models.IntegerField(blank=True, help_text='ID of the customer who referred this customer.', null=True, verbose_name='Referral Customer ID'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='referral_customer_id',
            field=models.IntegerField(blank=True, help_text='ID of the customer who referred this customer.', null=True, verbose_name='Referral Customer ID'),
        ),
    ]
