# Generated by Django 5.1.4 on 2024-12-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='le',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='test',
        ),
    ]
