# Generated by Django 5.2.1 on 2025-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_selected', 'Not Selected')], default='not_selected', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_selected', 'Not Selected')], default='not_selected', max_length=20, verbose_name='Gender'),
        ),
    ]
