# Generated by Django 5.2.7 on 2025-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Admin')], help_text='Profile type - null means incomplete registration', max_length=20, null=True, verbose_name='User Type'),
        ),
    ]
