# Generated by Django 5.2.5 on 2025-08-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_customer_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Referral Customer ID'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='referral_customer_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Referral Customer ID'),
        ),
    ]
