# Generated by Django 5.2.7 on 2025-10-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_user_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
