# Generated by Django 5.2.7 on 2025-11-06 08:08

import apps.users.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
    ]
