# Generated by Django 5.2.5 on 2025-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_referral_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_customer_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Referral Customer ID'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='referral_customer_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Referral Customer ID'),
        ),
    ]
