# Generated by Django 5.0.6 on 2024-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mobileuser_birthday_mobileuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuser',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
