# Generated by Django 5.2.5 on 2025-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_is_verified_historicalcustomer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inviter',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Referral Customer ID'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='inviter',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Referral Customer ID'),
        ),
    ]
