# Generated by Django 5.0.6 on 2024-08-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mobileuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
