# Generated by Django 5.1.7 on 2025-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_email_alter_historicalcustomer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='Is Profile Completed'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='Is Profile Completed'),
        ),
    ]
