# Generated by Django 5.2.7 on 2025-10-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminuser_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
