# Generated by Django 5.2.1 on 2025-08-06 13:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Should start with country code as (+966)', max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, help_text='Should start with country code as (+966)', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
