# Generated by Django 5.1.1 on 2024-09-09 07:14

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mobileuser_email_alter_mobileuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuser',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='users/'),
        ),
    ]
