# Generated by Django 5.1.7 on 2025-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='can_access_money',
            field=models.BooleanField(default=False, help_text='Allow this user to access money like process wallet money', verbose_name='Can access money'),
        ),
    ]
