# Generated by Django 5.2.5 on 2025-10-04 20:14

import django.contrib.gis.db.models.fields
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Location Point')),
                ('description', models.TextField(verbose_name='Description')),
                ('map_description', models.TextField(default='', help_text='Description for the map view', verbose_name='Map Description')),
                ('location_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], max_length=10, verbose_name='Location Type')),
                ('map_image', models.ImageField(blank=True, help_text='Image of the location on the map', null=True, upload_to='location/map_images/', verbose_name='Map Image')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('flag', models.ImageField(upload_to='flags', verbose_name='Flag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('app_install_money_inviter_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('app_install_money_inviter', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Money awarded to inviter when invitee installs the app.', max_digits=14, verbose_name='App Install Money - Inviter')),
                ('app_install_money_invitee_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('app_install_money_invitee', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Money awarded to invitee when they install the app.', max_digits=14, verbose_name='App Install Money - Invitee')),
                ('order_money_inviter_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('order_money_inviter', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Money awarded to inviter when invitee places first order.', max_digits=14, verbose_name='Order Money - Inviter')),
                ('order_money_invitee_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('order_money_invitee', djmoney.models.fields.MoneyField(decimal_places=2, help_text='Money awarded to invitee when they place first order.', max_digits=14, verbose_name='Order Money - Invitee')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
