# Generated by Django 5.2.5 on 2025-10-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customer', verbose_name='Customer'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('app_install_money_inviter_currency', models.F('currency'))), name='app_install_money_inviter_currency_consistency', violation_error_message='App install money inviter currency must match country currency.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('app_install_money_invitee_currency', models.F('currency'))), name='app_install_money_invitee_currency_consistency', violation_error_message='App install money invitee currency must match country currency.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('order_money_inviter_currency', models.F('currency'))), name='order_money_inviter_currency_consistency', violation_error_message='Order money inviter currency must match country currency.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('order_money_invitee_currency', models.F('currency'))), name='order_money_invitee_currency_consistency', violation_error_message='Order money invitee currency must match country currency.'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.country', verbose_name='Country'),
        ),
    ]
