# Generated by Django 5.2.5 on 2025-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='referral_points',
        ),
        migrations.RemoveField(
            model_name='country',
            name='referral_points_currency',
        ),
        migrations.AddField(
            model_name='country',
            name='app_install_money_invitee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money awarded to invitee when they install the app.', max_digits=14, verbose_name='App Install Money - Invitee'),
        ),
        migrations.AddField(
            model_name='country',
            name='app_install_money_inviter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money awarded to inviter when invitee installs the app.', max_digits=14, verbose_name='App Install Money - Inviter'),
        ),
        migrations.AddField(
            model_name='country',
            name='order_money_invitee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money awarded to invitee when they place first order.', max_digits=14, verbose_name='Order Money - Invitee'),
        ),
        migrations.AddField(
            model_name='country',
            name='order_money_inviter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Money awarded to inviter when invitee places first order.', max_digits=14, verbose_name='Order Money - Inviter'),
        ),
    ]
