# Generated by Django 5.2.1 on 2025-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('OM', 'Oman'), ('BH', 'Bahrain')], max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code'),
        ),
    ]
