# Generated by Django 5.2.5 on 2025-10-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Currency'),
        ),
    ]
