# Generated by Django 5.1.7 on 2025-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_description',
            field=models.TextField(default='', help_text='Description for the map view', verbose_name='Map Description'),
        ),
    ]
