# Generated by Django 5.2 on 2025-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_address_map_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_image',
            field=models.ImageField(blank=True, help_text='Image of the location on the map', null=True, upload_to='location/map_images/', verbose_name='Map Image'),
        ),
    ]
