# Generated by Django 5.2.5 on 2025-08-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='referral_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for referring a new user.', verbose_name='Referral Points'),
        ),
    ]
