# Generated by Django 5.2.5 on 2025-09-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_country_referral_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='app_install_money_invitee',
            field=models.DecimalField(decimal_places=2, help_text='Money awarded to invitee when they install the app.', max_digits=14, verbose_name='App Install Money - Invitee'),
        ),
        migrations.AlterField(
            model_name='country',
            name='app_install_money_inviter',
            field=models.DecimalField(decimal_places=2, help_text='Money awarded to inviter when invitee installs the app.', max_digits=14, verbose_name='App Install Money - Inviter'),
        ),
        migrations.AlterField(
            model_name='country',
            name='order_money_invitee',
            field=models.DecimalField(decimal_places=2, help_text='Money awarded to invitee when they place first order.', max_digits=14, verbose_name='Order Money - Invitee'),
        ),
        migrations.AlterField(
            model_name='country',
            name='order_money_inviter',
            field=models.DecimalField(decimal_places=2, help_text='Money awarded to inviter when invitee places first order.', max_digits=14, verbose_name='Order Money - Inviter'),
        ),
    ]
