# Generated by Django 5.2.5 on 2025-10-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_country_code_alter_country_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='country',
            name='app_install_money_inviter_currency_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='app_install_money_invitee_currency_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='order_money_inviter_currency_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='country',
            name='order_money_invitee_currency_consistency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
    ]
