# Generated by Django 5.2.5 on 2025-10-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_country_app_install_money_inviter_currency_consistency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
    ]
