# Generated by Django 5.2.5 on 2025-08-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_country_referral_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='referral_points',
        ),
    ]
