# Generated by Django 5.2.1 on 2025-05-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_rename_code_country_country_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_code',
            new_name='code',
        ),
    ]
