# Generated by Django 5.2.5 on 2025-08-18 11:16

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_remove_country_referral_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='referral_points',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='SAR', help_text='Points awarded for referring a new user.', max_digits=14, verbose_name='Referral Points'),
        ),
        migrations.AddField(
            model_name='country',
            name='referral_points_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default='SAR', editable=False, max_length=3),
        ),
    ]
