# Generated by Django 5.2.5 on 2025-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_country_referral_points_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='referral_points_currency',
        ),
        migrations.AlterField(
            model_name='country',
            name='referral_points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for referring a new user.', verbose_name='Referral Points'),
        ),
    ]
