# Generated by Django 5.2.5 on 2025-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_country_app_install_money_invitee_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('KW', 'Kuwait'), ('QA', 'Qatar'), ('OM', 'Oman'), ('BH', 'Bahrain'), ('UN', 'Unselected')], max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code'),
        ),
    ]
