# Generated by Django 5.2.5 on 2025-08-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_country_referral_points_currency_and_more'),
        ('location', '0007_alter_country_referral_points_and_more'),
    ]

    operations = [
    ]
