#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
#python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi \
    --bind 0.0.0.0:5000 \
    --chdir=/app \
    --workers 3 \
    --threads 2 \
    --worker-class gevent \
    --worker-connections 1000 \
    --max-requests 1000 \
    --max-requests-jitter 50 \
    --timeout 60 \
    --keep-alive 5
