# Generated by Django 5.2.7 on 2025-10-27 10:00

import djmoney.models.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price_before_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_before_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price before discount')),
                ('price_after_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_after_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price after discount')),
                ('payment_type', models.CharField(choices=[('charge_wallet', 'Charge Wallet'), ('other', 'Other')], max_length=15, verbose_name='Payment type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('payment_charge_id', models.CharField(default='', help_text='Reference ID from the payment gateway', max_length=255, verbose_name='Payment Reference')),
                ('bank_transaction_response', models.JSONField(blank=True, help_text='Full response from the bank', null=True, verbose_name='Bank Transaction Response')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Payment',
                'verbose_name_plural': 'historical Payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWallet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Balance')),
                ('is_use_wallet_in_payment', models.BooleanField(default=True, verbose_name='Use Wallet in Payment')),
                ('last_update', models.DateTimeField(blank=True, editable=False, verbose_name='Last Update')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Wallet',
                'verbose_name_plural': 'historical Wallets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWalletTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('transaction_note', models.TextField(blank=True, default='', max_length=1500)),
                ('attachment', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Wallet Transaction',
                'verbose_name_plural': 'historical Wallet Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_before_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price before discount')),
                ('price_after_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_after_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price after discount')),
                ('payment_type', models.CharField(choices=[('charge_wallet', 'Charge Wallet'), ('other', 'Other')], max_length=15, verbose_name='Payment type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('payment_charge_id', models.CharField(default='', help_text='Reference ID from the payment gateway', max_length=255, verbose_name='Payment Reference')),
                ('bank_transaction_response', models.JSONField(blank=True, help_text='Full response from the bank', null=True, verbose_name='Bank Transaction Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Balance')),
                ('is_use_wallet_in_payment', models.BooleanField(default=True, verbose_name='Use Wallet in Payment')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('transaction_note', models.TextField(blank=True, default='', max_length=1500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='wallet_transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
