# Generated by Django 5.1.7 on 2025-04-22 10:01

import django.db.models.deletion
import djmoney.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_customer_is_profile_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWallet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('is_use_wallet_in_payment', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical wallet',
                'verbose_name_plural': 'historical wallets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('is_use_wallet_in_payment', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWalletTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive')], max_length=20)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction')], max_length=20, verbose_name='Transaction Direction')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('transaction_note', models.TextField(blank=True, default='', max_length=1500)),
                ('attachment', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('action_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.adminuser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.wallet')),
            ],
            options={
                'verbose_name': 'historical Wallet Transaction',
                'verbose_name_plural': 'historical Wallet Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive')], max_length=20)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('KWD', 'Kuwaiti Dinar'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('direction', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction')], max_length=20, verbose_name='Transaction Direction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_note', models.TextField(blank=True, default='', max_length=1500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='wallet_transactions')),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.adminuser')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
            },
        ),
    ]
