# Generated by Django 5.2.5 on 2025-10-05 12:00

import django.db.models.deletion
import djmoney.models.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price_before_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_before_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price before discount')),
                ('price_after_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_after_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price after discount')),
                ('payment_type', models.CharField(choices=[('other', 'Other')], max_length=15, verbose_name='Payment type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('payment_charge_id', models.CharField(default='', help_text='Reference ID from the payment gateway', max_length=255, verbose_name='Payment Reference')),
                ('bank_transaction_response', models.JSONField(blank=True, help_text='Full response from the bank', null=True, verbose_name='Bank Transaction Response')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.customer', verbose_name='Customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Payment',
                'verbose_name_plural': 'historical Payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_before_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price before discount')),
                ('price_after_discount_currency', djmoney.models.fields.CurrencyField(choices=[('BHD', 'Bahraini Dinar'), ('EGP', 'Egyptian Pound'), ('JOD', 'Jordanian Dinar'), ('KWD', 'Kuwaiti Dinar'), ('LBP', 'Lebanese Pound'), ('OMR', 'Omani Rial'), ('QAR', 'Qatari Riyal'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham')], default=None, editable=False, max_length=3)),
                ('price_after_discount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Price after discount')),
                ('payment_type', models.CharField(choices=[('other', 'Other')], max_length=15, verbose_name='Payment type')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('payment_charge_id', models.CharField(default='', help_text='Reference ID from the payment gateway', max_length=255, verbose_name='Payment Reference')),
                ('bank_transaction_response', models.JSONField(blank=True, help_text='Full response from the bank', null=True, verbose_name='Bank Transaction Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='payment_pay_custome_b24458_idx')],
            },
        ),
    ]
