# Generated by Django 5.2.5 on 2025-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30),
        ),
    ]
