# Generated by Django 5.2.5 on 2025-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral')], max_length=20),
        ),
    ]
