# Generated by Django 5.1.7 on 2025-04-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_type_historicalwallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwallettransaction',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='direction',
        ),
    ]
