# Generated by Django 5.2.8 on 2026-01-08 09:49

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='action_by',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='transaction_note',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Transaction Note'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='historicalwallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payment.wallet', verbose_name='Wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='action_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Action By'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='wallet_transactions', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_note',
            field=models.TextField(blank=True, default='', max_length=1500, verbose_name='Transaction Note'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('CHARGING', 'Charging'), ('ORDER_PAYMENT', 'Order Payment'), ('CANCEL_ORDER', 'Cancel Order'), ('SHARE', 'Share'), ('CASH_RECEIVE', 'Cash Receive'), ('REFERRAL', 'Referral'), ('REFERRAL_APP_INSTALL_INVITER', 'Referral - App Install (Inviter)'), ('REFERRAL_APP_INSTALL_INVITEE', 'Referral - App Install (Invitee)'), ('REFERRAL_ORDER_INVITER', 'Referral - First Order (Inviter)'), ('REFERRAL_ORDER_INVITEE', 'Referral - First Order (Invitee)')], max_length=30, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.wallet', verbose_name='Wallet'),
        ),
    ]
