# Generated by Django 5.2.7 on 2025-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_historicalpayment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('charge_wallet', 'Charge Wallet'), ('other', 'Other')], max_length=15, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('charge_wallet', 'Charge Wallet'), ('other', 'Other')], max_length=15, verbose_name='Payment type'),
        ),
    ]
