name: Check Branch Sync

on:
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: read

jobs:
  check_branch_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check Branch Up-to-date with Main
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "❌ Branch is out-of-date with 'main'. Please rebase or merge."
            exit 1
          fi
