name: Docker Compose Test (PR)

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  docker_compose_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Django Image with Cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: projectname_django:latest
          build-args: |
            is_local=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Setup Environment File
        run: cp dummy.env .env

      - name: Start Services
        run: docker compose -f docker-compose.local.yml up -d postgres

      - name: Wait for Postgres
        run: |
          timeout 60 bash -c 'until docker compose -f docker-compose.local.yml exec postgres pg_isready; do sleep 2; done'

      - name: Run All Django Commands in Single Container
        run: |
          docker compose -f docker-compose.local.yml run --rm django bash -c "
            python manage.py makemigrations --check --dry-run &&
            python manage.py migrate --noinput &&
            python manage.py check &&
            pytest
          "

      - name: Tear down Stack
        if: always()
        run: docker compose -f docker-compose.local.yml down -v
